version: 2.1
executors:
  golang:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - run: make lint
  test:
    executor: golang
    steps:
      - checkout
      - run: make test
  build:
    executor: golang
    working_directory: /work
    parameters:
      os:
        type: string
      arch:
        type: string
    steps:
      - checkout
      - run: make OS=<< parameters.os >> ARCH=<< parameters.arch >> build
      - persist_to_workspace:
          root: /work
          paths:
            - artifacts/*
  test-kind:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      GOPATH: /home/circleci/.go_workspace
    steps:
      - checkout
      - run:
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.13.11
            curl -fsL https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | sudo tar xzf - -C /usr/local
      - run:
          command: |
            sudo curl -sLf https://storage.googleapis.com/kubernetes-release/release/v1.17.2/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
            sudo chmod +x /usr/local/bin/kubectl
      - run: make build
      - run: make kindtest
  create-tag:
    executor: golang
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:bb:b1:67:e0:69:82:54:ec:53:6a:fb:40:0d:47:bb"
      - checkout
      - run:
          command: |
            TAG=v$(cat VERSION)
            if git show-ref --tags | grep -q "refs/tags/${TAG}$"
            then
              echo "Already released version, skip"
              exit
            else
              git tag ${TAG}
              git push git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git ${TAG}
            fi
  release:
    executor: golang
    working_directory: /work
    steps:
      - attach_workspace:
          at: /work
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test
      - test-kind:
          requires:
            - lint
            - test
      - create-tag:
          requires:
            - test-kind
          filters:
            branches:
              only: master
  create-release:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, darwin, windows]
              arch: [amd64]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
